### PR TITLE
fix invalid return on deserialize function

### PR DESCRIPTION
**Pull request by sung-goo-kim**
fix invalid return on `_@(message.structure.namespaced_type.name)__cdr_deserialize` function

- It should return bool type, but returning string

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Good catch.  I'll run CI on this.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12224/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7207/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9949/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12123/)

**Comment by clalancette** [comment]
So it looks like this PR is pushing the auto-generated code above the cpplint limit of 500 statements per function.  What's going to have to happen is that this function (`*__cdr_deserialize`) is going to have to get broken into smaller helper functions.  I'm sorry @sung-goo-kim ; this is no fault of yours, but we have to find some fix for this before this PR can go in.

**Comment by dirk-thomas** [comment]
Since the length of the generated code depends on the number of fields in the message I don't think splitting this into separate functions is a viable workaround.

I would suggest to append `  // NOLINT(readability/fn_size)` after the closing curly brace of the function definition. See e.g. https://github.com/ros2/rosidl/blob/99e05f8e0be75f3840f6092d69dbd577088f62e1/rosidl_generator_cpp/resource/msg__traits.hpp.em#L130

@sung-goo-kim Can you please update the patch accordingly and check that the test passes locally for you. Thanks.

**Comment by clalancette** [comment]
I rebased and added the `NOLINT` change as suggested by @dirk-thomas .  Here's another CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12477/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7444/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10190/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12396/)

**Comment by sung-goo-kim** [comment]
@clalancette Thanks for the fix

**Review by clalancette — APPROVED** [review]

**Pull request merged**
