### PR TITLE
pass macro dep to cppcheck

### PR DESCRIPTION
**Pull request by claireyywang**
part of the effort to pin cppcheck 2.0, ros2/ros2#942
Signed-off-by: claireyywang <22240514+claireyywang@users.noreply.github.com>

### CODE REVIEW

**Comment by claireyywang** [comment]
CI 
linux [Build Status](https://ci.ros2.org/job/ci_linux/11327/)
linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/6565/)
osx [Build Status](https://ci.ros2.org/job/ci_osx/9291/)
windows [Build Status](https://ci.ros2.org/job/ci_windows/11223/)

**Comment by claireyywang** [comment]
@ros-pull-request-builder retest please

**Comment by sloretz** [comment]
@claireyywang looks like there's a merge conflict. Mind rebasing?

**Comment by clalancette** [comment]
This is very old, and we aren't going to pursue this anymore.  Closing.

**Pull request closed without merging**
